name: backend-ci.yml
on:
  push:
    branches:
      - chore/13-ci-cd
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    services:
      mysql:
        image: mysql.8.4.11
        env:
          MYSQL_DATABASE: database_test
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p root_password" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # 추후 setup-gradle로 변경할 것.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test