name: backend-ci.yml
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # 추후 setup-gradle로 변경할 것.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test